#!/bin/bash
# makevideos  Copyright (C) 2026  Dominique C. Michel
# This program comes with ABSOLUTELY NO WARRANTY; for details see the LICENSE file.
# This is free software, and you are welcome to redistribute it
# under certain conditions; for details see the LICENSE file.

# make vids at given fps
# Usage:	makevideos <fps>
# where 0 < fps > infini

videoname="Clapp"

usage(){
	echo "$0 <fps>"
	echo "where <fps> is an integer with 1 or 2 digits and is not 0."
	exit 1
}

input=$1
re='^[[:digit:]]{1,2}$'
re1='^[[:digit:]]{1}$'
if [[ $input =~ $re ]] && [[ $input != 0 ]] && [[ $input != 00 ]]; then
	SUF="${input}"
	if [[ $input =~ $re1 ]]; then
		SUF="0${input}"
	fi
else usage
fi

makevideo() {
# on my sytem mencoder gives unreadable files with -ovc raw, use ffmpeg
ffmpeg -framerate "${1}" -pattern_type glob -i "*.png" -c:v libx264  "${videoname}_fps${SUF}".avi
#    mencoder mf://*.png -mf w=800:h=600:fps=${1}:type=png -ovc copy -oac copy -o ${videoname}_fps${1}.avi
ffmpeg -i "${videoname}"_fps"${SUF}".avi -vf negate "${videoname}_fps${SUF}"_raw.avi
#    mencoder mf://*.png -mf w=800:h=600:fps=${1}:type=png -ovc raw -oac copy -o ${videoname}_raw_fps${1}.avi
#    mencoder mf://@index.txt -mf w=800:h=600:fps=${1}:type=png -ovc raw -oac copy -o ${videoname}_raw_alt_fps${1}.avi
#    mencoder mf://@index.txt -mf w=800:h=600:fps=${1}:type=png -ovc copy -oac copy -o ${videoname}_alt_fps${1}.avi
}

playvideo() {
mpv "${videoname}"_fps"${SUF}".avi
mpv "${videoname}"_fps"${SUF}"_raw.avi
#    mplayer ${videoname}_raw_alt_fps${1}.avi
#    mplayer ${videoname}_alt_fps${1}.avi
}

makevideo $1
playvideo $1


